name: flutter_siren_2
description: One way to notify users when a new version of your app is available and prompt them to upgrade.
version: '1.2.1'
homepage: https://github.com/laurence-trippen/flutter_siren_2
issue_tracker: https://github.com/diegocosta/flutter_siren/issues

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  package_info_plus: ^5.0.1
  url_launcher: ^6.0.12
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: